
export const SKILLS = [
  'Python',
  'JavaScript',
  'React',
  'Node.js',
  'Engineering Drawing',
  'Physics',
  'Calculus',
  'Linear Algebra',
  'Data Structures',
  'Algorithms',
  'Git',
  'Web Development',
  'CAD',
  'MATLAB',
  'Java',
  'Spring Boot',
  'UI/UX Design',
  'Figma',
  'HTML/CSS',
  'Databases',
  'Machine Learning',
  'Thermodynamics',
  'Circuit Design',
];
